### ISSUE TITLE
Question: is playing a sound is required for the workaround?

### ISSUE THREAD

**Issue by vpkopylov** [intbyte-100/matebook-d15-linux-soundfix#10]
I tried this workaround with Huawei Matebook 16s on Arch Linux and it works!

Meanwhile I noticed that when I run mbsoundfix plasma always shows it as playing some sound and I  can hear some noise in my bluetooth headphones. 
As far as I understood from sources the workaround does two things:
1. [Runs](https://github.com/intbyte-100/matebook-d15-linux-soundfix/blob/f1569807d22390c0cc44933d314682316a54ea7d/main.c#L60) commands that unmutes  `Headphone` and `DAC` controls.  (the second one doesn't exist on my machine, but not so important)
2. Endlessly [plays](https://github.com/intbyte-100/matebook-d15-linux-soundfix/blob/f1569807d22390c0cc44933d314682316a54ea7d/main.c#L65) a tone sound using pipewire lib (at least it is very close to [this example](https://docs.pipewire.org/page_tutorial4.html) in pipewire docs)

The thing that really makes a difference for me is running `amixer -c 0 sset Headphone on 100`, this is enough to start speakers working, but maybe things are different for other models? Can you please elaborate more on how the second part works?

**Comment by intbyte-100** [comment]
On the matebook d15, after stopping the playback of all audio sources, the audio card goes to sleep, which causes a loud click on this laptop model. To solve this problem, an eternal quiet sound is started to prevent the audio card from turning off.

**Comment by vpkopylov** [comment]
Thanks for the explanation! Interesting that I don't have this loud click problem (at least I didn't notice such behavior), maybe it's because Matebook 16s uses another sound chipset (Conexant SN6140) I would recommend putting details about how the fix works and the reasoning for playing this quiet sound into README for clarity. We can close this issue.
